# Generated by Django 3.2.8 on 2021-10-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
